name: starter_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3
  pin_entry_text_field: ^0.1.4
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.11.1
  flutter_screenutil: ^2.3.1
  font_awesome_flutter: ^8.5.0
  line_awesome_flutter: ^1.0.1
  flutter_markdown: ^0.5.0
  flutter_cmoon_icons: ^0.1.0
  international_phone_field: ^0.1.1
  http: ^0.12.2
  fluttertoast: ^7.1.5
  shimmer: ^1.1.2
  flutter_slidable: ^0.5.7
  #device preview
  device_preview: ^0.4.5
  #dependency injection & state mgmt
  get:
  get_it: ^4.0.4
  provider: ^3.0.1
  #internationalization
  intl: ^0.16.1
  #icons
  cupertino_icons: ^0.1.3
  #animation
  animated_text_kit: ^2.0.0
  bottom_navy_bar: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.2
  flutter_launcher_icons: "^0.8.0"

flutter_native_splash:
  image: assets/logo.png
  color: "FFFFFF"
  image_dark: assets/logo.png
  color_dark: "414141"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/SFProText.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

